console:
  max_message_size_bytes: 409600
logger:
  level: "DEBUG"
runtime:
  env:
    - "TOURNAMENT_API_URL=hi"
    - "GAME_CLIENT_ID=hello"
    - "GAME_CLIENT_SECRET=world"
  js_entrypoint: "build/index.js"
session:
  token_expiry_sec: 7200 # 2 hours
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072
