name: Build and deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-app:
    uses: cosmic-org/workflow-library/.github/workflows/deploy.yml@main
    with:
      repository_url: https://github.com/cosmic-org/cosmic-engine.git
    secrets: inherit
